config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :usuarios, param: :nome
  resources :anuncios
  resources :sessions

  get    'home' => 'pages#home'
  get    'sobre' => 'pages#sobre'
  get    'contato' => 'pages#contato'
  get    'suporte' => 'pages#suporte'

  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/administrador.rb
class Administrador < ActiveRecord::Base
end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  # has_one :livro
  belongs_to :usuario

  has_attached_file :imagem_capa unless Rails.env.production?
  has_attached_file :imagem_capa, storage: :imgur if Rails.env.production?

  scope :por_tipo, -> (t) { where "tipo_anuncio='#{t}'" }
  scope :emprestimo, -> { por_tipo('empréstimo') }
  scope :troca, -> { por_tipo('troca') }

  validates :tipo_anuncio, inclusion: {in: %w(troca empréstimo)}
  validates :prazo_emprestimo, numericality: {only_integer: true}, if: :emprestimo?
  validates :troco_por, presence: true, if: :troca?

  validates_attachment_content_type :imagem_capa, :content_type => /\Aimage\/.*\Z/

  def opcao=(opc)
    case tipo_anuncio
    when 'troca'
      troco_por = opc
    when 'empréstimo'
      prazo_emprestimo = opc
    end
  end

  def opcao
    case tipo_anuncio
    when 'troca'
      troco_por
    when 'empréstimo'
      prazo_emprestimo
    end
  end

  def troca?
    return tipo_anuncio == 'troca'
  end
  def emprestimo?
    return tipo_anuncio == 'empréstimo'
  end
end

app/models/usuario.rb
require 'hashifiable'

class Usuario < ActiveRecord::Base
  extend Hashifiable
  hashify :nome, :email, :senha

  # has_many :livros, dependent: :destroy
  has_many :anuncios, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :termos_de_servico, acceptance: true
  validates :nome, presence: true
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: /\A[^@]+ @ (?:[^@\.]+ \.)+ [^@\.]+\z/ix }

  has_secure_password

  def to_param
    nome
  end
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  before_action :set_anuncio, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @anuncio = Anuncio.new
  end

  def create
    @anuncio = Anuncio.new (anuncio_params)
    @anuncio.usuario = current_user

    if @anuncio.save
      flash[:success] = "Anúncio criado com sucesso"
      redirect_to current_user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @anuncio.update(anuncio_params)
      redirect_to @anuncio, notice: 'Anuncio was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @anuncio.destroy
    redirect_to anuncios_url, notice: 'Anuncio was successfully destroyed.'
  end

  private
    def set_anuncio
      @anuncio = Anuncio.find(params[:id])
    end

    def anuncio_params
      whitelist = [:titulo, :autor, :edicao, :idioma, :tipo_anuncio, :troco_por, :prazo_emprestimo, :imagem_capa]
      params.require(:anuncio).permit(whitelist)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def sobre
  end
  def contato
  end
  def suporte
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to current_user
    end
  end

  def create
    user = Usuario.find_by_email(params[:session][:email])
    unless user
      flash[:danger] = 'Usuário inválido ♿'
      render :new
    else
      unless user.authenticate(params[:session][:password])
        flash[:danger] = 'Senha inválida ♿'
        render :new
      else
        session[:user_id] = user.id
        flash[:success] = 'You are logged in, modafoca!'
        redirect_to user
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, flash: {success: 'Logged out!'}
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      log_in @usuario
      flash[:success] = "Bem-vindo ao TemLivro!"
      redirect_to @usuario
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    if @usuario.update(usuario_params)
      redirect_to @usuario, notice: 'Usuario was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find_by_nome(params[:nome])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      whitelist = [:nome, :email, :password, :password_confirmation, :termos_de_servico]
      params.require(:usuario).permit(whitelist)
    end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
  def announce_fields
    campos = []
    campos << {field: :titulo, label: 'Título', type: :text_field}
    campos << {field: :autor, label: 'Autor', type: :text_field}
    campos << {field: :edicao, label: 'Edição', type: :number_field}
    campos << {field: :idioma, label: 'Idioma', type: :text_field}

    campos << {field: :tipo_anuncio, label: 'Opção', type: :radio_button}
    campos << {field: :observação, label: 'Observação', type: :text_field}
    campos << {field: :opcao, label: @label_anuncio, type: :text_field}

    campos << {field: :imagem_capa, label: 'Foto', type: :file_field}
    # campos << {field: :password, label: 'Senha', type: :password_field}
    # campos << {field: :password_confirmation, label: 'Confirme sua senha', type: :password_field}
    # campos << {field: :termos_de_servico, label: 'Aceito os termos de serviço', type: :check_box, require: :signup?}
    campos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def link_toggle_accordion(section)
    link_to section.capitalize, '#' + section_results(section),
            class: 'accordion-toggle', 'data-toggle' => 'collapse'
  end

  def section_results(section)
    "#{section}-resultados"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def log_in(user)
     session[:user_id] = user.id
   end

   def remember(user)
     user.remember
     cookies.permanent.signed[:user_id] = user.id
     cookies.permanent[:remember_token] = user.remember_token
   end

   def current_user
     @current_user ||= Usuario.find_by(id: session[:user_id])
   end

   def logged_in?
     !current_user.nil?
   end

   def log_out
     session.delete(:user_id)
     @current_user = nil
   end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
  def signup?
    return ['new', 'create'].include? params[:action]
  end

  def user_fields
    campos = []
    campos << {field: :nome, label: 'Nome Completo', type: :text_field}
    campos << {field: :email, label: 'Email', type: :text_field}
    campos << {field: :password, label: 'Senha', type: :password_field}
    campos << {field: :password_confirmation, label: 'Confirme sua senha', type: :password_field}
    # campos << {field: :termos_de_servico, label: 'Aceito os termos de serviço', type: :check_box, require: :signup?}
    campos
  end

  # def required_field?(field)
  #   resultado = !field[:require]
  #   resultado ||= send field[:require]
  # end
end

app/views/anuncios/_form.html.erb
<%= form_for(@anuncio, multipart: true, html: {class: 'form-horizontal'}) do |f| %>
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anuncio.errors.count, "error") %> prohibited this anuncio from being saved:</h2>

      <ul>
      <% @anuncio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @anuncio.tipo_anuncio ||= 'troca' %>
  <% @label_anuncio = 'Troco Por' if @anuncio.troca? %>
  <% @label_anuncio = 'Prazo de Empréstimo' if @anuncio.emprestimo? %>

  <% announce_fields.each do |field, label| %>
    <div class="form-group">
      <% if field.include? :label %>
        <%= f.label field[:label], class: 'col-sm-3 control-label', for: 'anuncio_' +  field[:field].to_s %>
      <% else field[:sm_offset] = true end %>
    <% if field.include? :sm_offset %>
      <div class="col-sm-9 col-sm-offset-3"> <% else %> <div class="col-sm-9">
    <% end %>
      <% if field[:type] == :radio_button %>
          <%= f.collection_radio_buttons(field[:field], Anuncio.group(:tipo_anuncio).select(:tipo_anuncio), field[:field], field[:field]) do |b|
            b.label {b.radio_button(style: 'margin: 0 5px 0 10px', class: 'tipo_anuncio_radio') + " #{b.text.capitalize} "}
          end  %>
      <% else %>
        <%= f.send field[:type], field[:field], class: 'col-sm-9 form-control', placeholder: field[:label] %>
      <% end %>
      </div>
    </div>
  <% end %>

  <div class="actions form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <%= f.submit class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/anuncios/_label_opcao.html.erb
<% span_class = "label label-#{anuncio.tipo_anuncio}"%>
<% label_texto = 'Troco por' if anuncio.troca? %>
<% label_texto = 'Empresto por' if anuncio.emprestimo? %>
<p><%= content_tag :span, label_texto, class: span_class %> <%= anuncio.opcao %> </p>

app/views/anuncios/_livro.html.erb
<div class="col-md-6 col-xs-12">
  <div href="#" class="thumbnail">
    <%= image_tag anuncio.imagem_capa  %>
    <div class="caption">
      <%= link_to content_tag(:h3, anuncio.titulo), anuncio %>
      <p><strong>Autor: </strong><%= anuncio.autor %></p>
      <p><strong>Edição: </strong><%= anuncio.edicao %></p>
      <p><strong>Editora: </strong><%= anuncio.autor %></p>
      <p><strong>Idioma: </strong><%= anuncio.idioma %></p>

      <%= render 'anuncios/label_opcao', anuncio: anuncio %>

    </div>
  </div>
</div>

app/views/anuncios/edit.html.erb
<h1>Editing Anuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @anuncio %> |
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/new.html.erb
<h1>Cadastro</h1>
<%= render 'form' %>
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/show.html.erb
<%= render 'livro', anuncio: @anuncio %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="text-center center-block" style="max-width:290px">
      <ul class="nav navbar-nav" role="navigation">
        <li><%= link_to 'Home', root_url, class: 'text-muted' %></li>
        <li><%= link_to 'Sobre', sobre_url, class: 'text-muted' %></li>
        <li><%= link_to 'Ajuda', suporte_url, class: 'text-muted' %></li>
        <li><%= link_to 'Contato', contato_url, class: 'text-muted' %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to(image_tag('logo_texto.png', style: 'max-width:100px; margin-top: -7px;'), root_url)%>
    </div>

    <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <div class="collapse navbar-collapse navHeaderCollapse">

      <!-- BUSCA -->
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Busca">
        </div>
        <button type="submit" class="btn btn-default">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </form>

      <!-- OPCOES USUARIO -->
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li> <%= link_to current_user.nome, current_user %> </li>
        <li> <%= link_to 'Logout', logout_path, method: :delete, data: {confirm: 'Tem certeza que deseja sair do TemLivro?'} %> </li>
      <% else %>
        <li> <%= link_to 'Cadastre-se', signup_path %> </li>
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown"> Login </a>
          <!-- LOGIN POPUP -->
          <div class="dropdown-menu" >
            <div class="input-group">
              <%= render 'sessions/form' %>
            </div>
          </div>
        </li>
      <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teste</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=devide-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) unless Rails.env.production? %>
    <%= console unless Rails.env.production? %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/_secao_home.html.erb
<div class="col-sm-12">
  <h1><%= link_toggle_accordion(section) %></h1>
    <div id='<%= section_results(section) %>'  class="panel-collapse collapse in">
      <div id="<%= section %>" class="row">

        <% Anuncio.por_tipo(section).last(2).each do |anuncio| %>
        <!-- Item Seção -->
        <%= render 'anuncios/livro', anuncio: anuncio %>
        <!-- Fim Item Seção -->
        <% end %>
      </div>
    </div>
</div>

app/views/pages/contato.html.erb
<h1>Contate-nos!</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>
    <%= image_tag 'logo_texto.png', style: 'max-width: 300px' %>
  </h1>
  <p>
    troque ou empreste seus livros <br/>
    <span class="glyphicon glyphicon-book"></span>
  </p>
  <p><%= link_to 'Cadastre-se', signup_path, class: 'btn btn-primary btn-lg' %></p>
</div>
<%= render 'secao_home', section: 'troca' %>
<%= render 'secao_home', section: 'empréstimo' %>

app/views/pages/sobre.html.erb
<h1>Sobre a TemLivro</h1>

app/views/pages/suporte.html.erb
<h1>Suporte</h1>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario, html: {class: 'form-horizontal'}) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% user_fields.each do |field, label| %>
    <div class="form-group">
      <%= f.label field[:label], class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= f.send field[:type], field[:field], class: 'col-sm-9 form-control' %>
      </div>
    </div>
  <% end %>

  <% if signup? %>
    <div class="form-group">
      <div class="col-sm-9 col-sm-offset-3">
        <%= f.check_box :termos_de_servico %>
        <%= f.label :Aceito_os_termos_de_Uso, for: :usuario_termos_de_servico %>
      </div>
    </div>
  <% end %>

  <div class="actions form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <%= f.submit class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.password_digest %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>